// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockConfigWriter is an autogenerated mock type for the ConfigWriter type
type MockConfigWriter struct {
	mock.Mock
}

type MockConfigWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigWriter) EXPECT() *MockConfigWriter_Expecter {
	return &MockConfigWriter_Expecter{mock: &_m.Mock}
}

// UpdateHeist provides a mock function with given fields: amount
func (_m *MockConfigWriter) UpdateHeist(amount int) error {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHeist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigWriter_UpdateHeist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHeist'
type MockConfigWriter_UpdateHeist_Call struct {
	*mock.Call
}

// UpdateHeist is a helper method to define mock.On call
//   - amount int
func (_e *MockConfigWriter_Expecter) UpdateHeist(amount interface{}) *MockConfigWriter_UpdateHeist_Call {
	return &MockConfigWriter_UpdateHeist_Call{Call: _e.mock.On("UpdateHeist", amount)}
}

func (_c *MockConfigWriter_UpdateHeist_Call) Run(run func(amount int)) *MockConfigWriter_UpdateHeist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockConfigWriter_UpdateHeist_Call) Return(_a0 error) *MockConfigWriter_UpdateHeist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigWriter_UpdateHeist_Call) RunAndReturn(run func(int) error) *MockConfigWriter_UpdateHeist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigWriter creates a new instance of MockConfigWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigWriter {
	mock := &MockConfigWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
