// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	ports "streamgogambler/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockChatClient is an autogenerated mock type for the ChatClient type
type MockChatClient struct {
	mock.Mock
}

type MockChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatClient) EXPECT() *MockChatClient_Expecter {
	return &MockChatClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx
func (_m *MockChatClient) Connect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockChatClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatClient_Expecter) Connect(ctx interface{}) *MockChatClient_Connect_Call {
	return &MockChatClient_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockChatClient_Connect_Call) Run(run func(ctx context.Context)) *MockChatClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChatClient_Connect_Call) Return(_a0 error) *MockChatClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatClient_Connect_Call) RunAndReturn(run func(context.Context) error) *MockChatClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *MockChatClient) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockChatClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *MockChatClient_Expecter) Disconnect() *MockChatClient_Disconnect_Call {
	return &MockChatClient_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *MockChatClient_Disconnect_Call) Run(run func()) *MockChatClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatClient_Disconnect_Call) Return(_a0 error) *MockChatClient_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatClient_Disconnect_Call) RunAndReturn(run func() error) *MockChatClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function with given fields: channel
func (_m *MockChatClient) Join(channel string) {
	_m.Called(channel)
}

// MockChatClient_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockChatClient_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - channel string
func (_e *MockChatClient_Expecter) Join(channel interface{}) *MockChatClient_Join_Call {
	return &MockChatClient_Join_Call{Call: _e.mock.On("Join", channel)}
}

func (_c *MockChatClient_Join_Call) Run(run func(channel string)) *MockChatClient_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChatClient_Join_Call) Return() *MockChatClient_Join_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_Join_Call) RunAndReturn(run func(string)) *MockChatClient_Join_Call {
	_c.Run(run)
	return _c
}

// OnBan provides a mock function with given fields: handler
func (_m *MockChatClient) OnBan(handler func(ports.BanEvent)) {
	_m.Called(handler)
}

// MockChatClient_OnBan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnBan'
type MockChatClient_OnBan_Call struct {
	*mock.Call
}

// OnBan is a helper method to define mock.On call
//   - handler func(ports.BanEvent)
func (_e *MockChatClient_Expecter) OnBan(handler interface{}) *MockChatClient_OnBan_Call {
	return &MockChatClient_OnBan_Call{Call: _e.mock.On("OnBan", handler)}
}

func (_c *MockChatClient_OnBan_Call) Run(run func(handler func(ports.BanEvent))) *MockChatClient_OnBan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(ports.BanEvent)))
	})
	return _c
}

func (_c *MockChatClient_OnBan_Call) Return() *MockChatClient_OnBan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_OnBan_Call) RunAndReturn(run func(func(ports.BanEvent))) *MockChatClient_OnBan_Call {
	_c.Run(run)
	return _c
}

// OnConnect provides a mock function with given fields: handler
func (_m *MockChatClient) OnConnect(handler func()) {
	_m.Called(handler)
}

// MockChatClient_OnConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnect'
type MockChatClient_OnConnect_Call struct {
	*mock.Call
}

// OnConnect is a helper method to define mock.On call
//   - handler func()
func (_e *MockChatClient_Expecter) OnConnect(handler interface{}) *MockChatClient_OnConnect_Call {
	return &MockChatClient_OnConnect_Call{Call: _e.mock.On("OnConnect", handler)}
}

func (_c *MockChatClient_OnConnect_Call) Run(run func(handler func())) *MockChatClient_OnConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockChatClient_OnConnect_Call) Return() *MockChatClient_OnConnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_OnConnect_Call) RunAndReturn(run func(func())) *MockChatClient_OnConnect_Call {
	_c.Run(run)
	return _c
}

// OnMessage provides a mock function with given fields: handler
func (_m *MockChatClient) OnMessage(handler func(ports.ChatMessage)) {
	_m.Called(handler)
}

// MockChatClient_OnMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnMessage'
type MockChatClient_OnMessage_Call struct {
	*mock.Call
}

// OnMessage is a helper method to define mock.On call
//   - handler func(ports.ChatMessage)
func (_e *MockChatClient_Expecter) OnMessage(handler interface{}) *MockChatClient_OnMessage_Call {
	return &MockChatClient_OnMessage_Call{Call: _e.mock.On("OnMessage", handler)}
}

func (_c *MockChatClient_OnMessage_Call) Run(run func(handler func(ports.ChatMessage))) *MockChatClient_OnMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(ports.ChatMessage)))
	})
	return _c
}

func (_c *MockChatClient_OnMessage_Call) Return() *MockChatClient_OnMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_OnMessage_Call) RunAndReturn(run func(func(ports.ChatMessage))) *MockChatClient_OnMessage_Call {
	_c.Run(run)
	return _c
}

// OnNotice provides a mock function with given fields: handler
func (_m *MockChatClient) OnNotice(handler func(string, string)) {
	_m.Called(handler)
}

// MockChatClient_OnNotice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnNotice'
type MockChatClient_OnNotice_Call struct {
	*mock.Call
}

// OnNotice is a helper method to define mock.On call
//   - handler func(string , string)
func (_e *MockChatClient_Expecter) OnNotice(handler interface{}) *MockChatClient_OnNotice_Call {
	return &MockChatClient_OnNotice_Call{Call: _e.mock.On("OnNotice", handler)}
}

func (_c *MockChatClient_OnNotice_Call) Run(run func(handler func(string, string))) *MockChatClient_OnNotice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string, string)))
	})
	return _c
}

func (_c *MockChatClient_OnNotice_Call) Return() *MockChatClient_OnNotice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_OnNotice_Call) RunAndReturn(run func(func(string, string))) *MockChatClient_OnNotice_Call {
	_c.Run(run)
	return _c
}

// OnReconnect provides a mock function with given fields: handler
func (_m *MockChatClient) OnReconnect(handler func() bool) {
	_m.Called(handler)
}

// MockChatClient_OnReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnReconnect'
type MockChatClient_OnReconnect_Call struct {
	*mock.Call
}

// OnReconnect is a helper method to define mock.On call
//   - handler func() bool
func (_e *MockChatClient_Expecter) OnReconnect(handler interface{}) *MockChatClient_OnReconnect_Call {
	return &MockChatClient_OnReconnect_Call{Call: _e.mock.On("OnReconnect", handler)}
}

func (_c *MockChatClient_OnReconnect_Call) Run(run func(handler func() bool)) *MockChatClient_OnReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func() bool))
	})
	return _c
}

func (_c *MockChatClient_OnReconnect_Call) Return() *MockChatClient_OnReconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatClient_OnReconnect_Call) RunAndReturn(run func(func() bool)) *MockChatClient_OnReconnect_Call {
	_c.Run(run)
	return _c
}

// Say provides a mock function with given fields: ctx, channel, message
func (_m *MockChatClient) Say(ctx context.Context, channel string, message string) error {
	ret := _m.Called(ctx, channel, message)

	if len(ret) == 0 {
		panic("no return value specified for Say")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channel, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatClient_Say_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Say'
type MockChatClient_Say_Call struct {
	*mock.Call
}

// Say is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - message string
func (_e *MockChatClient_Expecter) Say(ctx interface{}, channel interface{}, message interface{}) *MockChatClient_Say_Call {
	return &MockChatClient_Say_Call{Call: _e.mock.On("Say", ctx, channel, message)}
}

func (_c *MockChatClient_Say_Call) Run(run func(ctx context.Context, channel string, message string)) *MockChatClient_Say_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockChatClient_Say_Call) Return(_a0 error) *MockChatClient_Say_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatClient_Say_Call) RunAndReturn(run func(context.Context, string, string) error) *MockChatClient_Say_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatClient creates a new instance of MockChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatClient {
	mock := &MockChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
