// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageSender is an autogenerated mock type for the MessageSender type
type MockMessageSender struct {
	mock.Mock
}

type MockMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSender) EXPECT() *MockMessageSender_Expecter {
	return &MockMessageSender_Expecter{mock: &_m.Mock}
}

// Say provides a mock function with given fields: ctx, channel, message
func (_m *MockMessageSender) Say(ctx context.Context, channel string, message string) error {
	ret := _m.Called(ctx, channel, message)

	if len(ret) == 0 {
		panic("no return value specified for Say")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channel, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageSender_Say_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Say'
type MockMessageSender_Say_Call struct {
	*mock.Call
}

// Say is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - message string
func (_e *MockMessageSender_Expecter) Say(ctx interface{}, channel interface{}, message interface{}) *MockMessageSender_Say_Call {
	return &MockMessageSender_Say_Call{Call: _e.mock.On("Say", ctx, channel, message)}
}

func (_c *MockMessageSender_Say_Call) Run(run func(ctx context.Context, channel string, message string)) *MockMessageSender_Say_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMessageSender_Say_Call) Return(_a0 error) *MockMessageSender_Say_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSender_Say_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMessageSender_Say_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSender creates a new instance of MockMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSender {
	mock := &MockMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
