// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ports "streamgogambler/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockStatsProvider is an autogenerated mock type for the StatsProvider type
type MockStatsProvider struct {
	mock.Mock
}

type MockStatsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsProvider) EXPECT() *MockStatsProvider_Expecter {
	return &MockStatsProvider_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with no fields
func (_m *MockStatsProvider) GetStats() ports.BotStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 ports.BotStats
	if rf, ok := ret.Get(0).(func() ports.BotStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.BotStats)
	}

	return r0
}

// MockStatsProvider_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockStatsProvider_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockStatsProvider_Expecter) GetStats() *MockStatsProvider_GetStats_Call {
	return &MockStatsProvider_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockStatsProvider_GetStats_Call) Run(run func()) *MockStatsProvider_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsProvider_GetStats_Call) Return(_a0 ports.BotStats) *MockStatsProvider_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsProvider_GetStats_Call) RunAndReturn(run func() ports.BotStats) *MockStatsProvider_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsProvider creates a new instance of MockStatsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsProvider {
	mock := &MockStatsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
