// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ports "streamgogambler/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigStore is an autogenerated mock type for the ConfigStore type
type MockConfigStore struct {
	mock.Mock
}

type MockConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigStore) EXPECT() *MockConfigStore_Expecter {
	return &MockConfigStore_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function with no fields
func (_m *MockConfigStore) GetConfig() ports.BotConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 ports.BotConfig
	if rf, ok := ret.Get(0).(func() ports.BotConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.BotConfig)
	}

	return r0
}

// MockConfigStore_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockConfigStore_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockConfigStore_Expecter) GetConfig() *MockConfigStore_GetConfig_Call {
	return &MockConfigStore_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockConfigStore_GetConfig_Call) Run(run func()) *MockConfigStore_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigStore_GetConfig_Call) Return(_a0 ports.BotConfig) *MockConfigStore_GetConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigStore_GetConfig_Call) RunAndReturn(run func() ports.BotConfig) *MockConfigStore_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuth provides a mock function with no fields
func (_m *MockConfigStore) GetOAuth() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOAuth")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigStore_GetOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuth'
type MockConfigStore_GetOAuth_Call struct {
	*mock.Call
}

// GetOAuth is a helper method to define mock.On call
func (_e *MockConfigStore_Expecter) GetOAuth() *MockConfigStore_GetOAuth_Call {
	return &MockConfigStore_GetOAuth_Call{Call: _e.mock.On("GetOAuth")}
}

func (_c *MockConfigStore_GetOAuth_Call) Run(run func()) *MockConfigStore_GetOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigStore_GetOAuth_Call) Return(_a0 string) *MockConfigStore_GetOAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigStore_GetOAuth_Call) RunAndReturn(run func() string) *MockConfigStore_GetOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHeist provides a mock function with given fields: amount
func (_m *MockConfigStore) UpdateHeist(amount int) error {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHeist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigStore_UpdateHeist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHeist'
type MockConfigStore_UpdateHeist_Call struct {
	*mock.Call
}

// UpdateHeist is a helper method to define mock.On call
//   - amount int
func (_e *MockConfigStore_Expecter) UpdateHeist(amount interface{}) *MockConfigStore_UpdateHeist_Call {
	return &MockConfigStore_UpdateHeist_Call{Call: _e.mock.On("UpdateHeist", amount)}
}

func (_c *MockConfigStore_UpdateHeist_Call) Run(run func(amount int)) *MockConfigStore_UpdateHeist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockConfigStore_UpdateHeist_Call) Return(_a0 error) *MockConfigStore_UpdateHeist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigStore_UpdateHeist_Call) RunAndReturn(run func(int) error) *MockConfigStore_UpdateHeist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigStore creates a new instance of MockConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigStore {
	mock := &MockConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
