// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ports "streamgogambler/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigReader is an autogenerated mock type for the ConfigReader type
type MockConfigReader struct {
	mock.Mock
}

type MockConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigReader) EXPECT() *MockConfigReader_Expecter {
	return &MockConfigReader_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function with no fields
func (_m *MockConfigReader) GetConfig() ports.BotConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 ports.BotConfig
	if rf, ok := ret.Get(0).(func() ports.BotConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.BotConfig)
	}

	return r0
}

// MockConfigReader_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockConfigReader_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetConfig() *MockConfigReader_GetConfig_Call {
	return &MockConfigReader_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockConfigReader_GetConfig_Call) Run(run func()) *MockConfigReader_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetConfig_Call) Return(_a0 ports.BotConfig) *MockConfigReader_GetConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetConfig_Call) RunAndReturn(run func() ports.BotConfig) *MockConfigReader_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuth provides a mock function with no fields
func (_m *MockConfigReader) GetOAuth() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOAuth")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigReader_GetOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuth'
type MockConfigReader_GetOAuth_Call struct {
	*mock.Call
}

// GetOAuth is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetOAuth() *MockConfigReader_GetOAuth_Call {
	return &MockConfigReader_GetOAuth_Call{Call: _e.mock.On("GetOAuth")}
}

func (_c *MockConfigReader_GetOAuth_Call) Run(run func()) *MockConfigReader_GetOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetOAuth_Call) Return(_a0 string) *MockConfigReader_GetOAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetOAuth_Call) RunAndReturn(run func() string) *MockConfigReader_GetOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigReader creates a new instance of MockConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigReader {
	mock := &MockConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
