version: "2"
run:
  modules-download-mode: readonly
  build-tags:
    - ci
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 4
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G104
        - G404
        - G112
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      for-loops: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
          - gosec
          - unparam
        path: _test\.go
      - linters:
          - gosec
        path: fuzz_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/adapters/gui/.*
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - streamgogambler
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
